CREATE TABLE CALL_JY_LOG (
  id VARCHAR2(20 BYTE) NOT NULL ,
  sfzmhm VARCHAR2(20 BYTE) ,
  jkid VARCHAR2(10 BYTE) ,
  jkms VARCHAR2(255 BYTE) ,
  dyjg VARCHAR2(1 BYTE) ,
  jgnr VARCHAR2(255 BYTE) ,
  dyrq VARCHAR2(30 BYTE) ,
  dysj TIMESTAMP(6) 
);
ALTER TABLE CALL_JY_LOG ADD PRIMARY KEY (ID);
CREATE INDEX sfzmhm_index ON CALL_JY_LOG(SFZMHM);