CREATE TABLE CALL_JY_LOG (
  id VARCHAR2(50 BYTE) NOT NULL ,
  sfzmhm VARCHAR2(50 BYTE) ,
  jkid VARCHAR2(20 BYTE) ,
  jkms VARCHAR2(500 BYTE) ,
  dyjg VARCHAR2(1 BYTE) ,
  jgnr VARCHAR2(500 BYTE) ,
  dyrq VARCHAR2(30 BYTE) ,
  dysj TIMESTAMP(6),
  log_type VARCHAR2(30 BYTE)
);
ALTER TABLE CALL_JY_LOG ADD PRIMARY KEY (ID);
CREATE INDEX sfzmhm_index ON CALL_JY_LOG(SFZMHM);